# Generated by Django 5.1.14 on 2025-11-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0062_alter_credentials_credential_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchatmessagerequest',
            name='to',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('specific_user', 'Specific User'), ('everyone_but_host', 'Everyone But Host')], max_length=50),
        ),
    ]
