# Generated by Django 5.1.2 on 2025-11-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0063_bot_session_type_bot_zoom_rtms_stream_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='transcription_provider',
            field=models.IntegerField(blank=True, choices=[(1, 'Deepgram'), (2, 'Closed Caption From Platform'), (3, 'Gladia'), (4, 'OpenAI'), (5, 'Assembly AI'), (6, 'Sarvam'), (7, 'ElevenLabs'), (8, 'Kyutai'), (9, 'Custom Async')], null=True),
        ),
    ]


