# Generated by Django 5.1.2 on 2025-12-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0065_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomoauthconnection',
            name='is_local_recording_token_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zoomoauthconnection',
            name='is_onbehalf_token_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zoomoauthconnection',
            name='last_attempted_token_refresh_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoomoauthconnection',
            name='last_successful_token_refresh_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoomoauthconnection',
            name='token_refresh_task_enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoomoauthconnection',
            name='token_refresh_task_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
