# Generated by Django 5.1.2 on 2025-12-15 19:45

import json
import random
import string

from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations


ZOOM_OAUTH_CREDENTIAL_TYPE = 2


def convert_zoom_credentials_to_zoom_oauth_apps(apps, schema_editor):
    Credentials = apps.get_model('bots', 'Credentials')
    ZoomOAuthApp = apps.get_model('bots', 'ZoomOAuthApp')

    zoom_credentials = Credentials.objects.filter(credential_type=ZOOM_OAUTH_CREDENTIAL_TYPE)

    for credential in zoom_credentials:
        # Check if a ZoomOAuthApp already exists for this project
        if ZoomOAuthApp.objects.filter(project=credential.project).exists():
            print(f"ZoomOAuthApp already exists for project {credential.project.name}, skipping")
            continue

        # Decrypt the credential data
        if not credential._encrypted_data:
            print(f"No encrypted data for credential {credential.id} in project {credential.project.name}, skipping")
            continue

        f = Fernet(settings.CREDENTIALS_ENCRYPTION_KEY)
        decrypted_data = f.decrypt(bytes(credential._encrypted_data))
        credentials_dict = json.loads(decrypted_data.decode())

        client_id = credentials_dict.get('client_id')
        client_secret = credentials_dict.get('client_secret')

        if not client_id or not client_secret:
            print(f"No client id or client secret for credential {credential.id} in project {credential.project.name}, skipping")
            continue

        # Generate object_id for the new ZoomOAuthApp
        random_string = "".join(random.choices(string.ascii_letters + string.digits, k=16))
        object_id = f"zoa_{random_string}"

        # Create the new ZoomOAuthApp
        zoom_oauth_app = ZoomOAuthApp.objects.create(
            project=credential.project,
            object_id=object_id,
            client_id=client_id,
        )

        # Set the encrypted credentials
        new_credentials_dict = {'client_secret': client_secret}
        encrypted_data = f.encrypt(json.dumps(new_credentials_dict).encode())
        zoom_oauth_app._encrypted_data = encrypted_data
        zoom_oauth_app.save()
        print(f"Created ZoomOAuthApp {zoom_oauth_app.object_id} for project {credential.project.name} and credential {credential.id}")


def reverse_conversion(apps, schema_editor):
    # No reverse operation - we don't want to delete created ZoomOAuthApps
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0066_zoomoauthconnection_is_local_recording_token_supported_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_zoom_credentials_to_zoom_oauth_apps, reverse_conversion),
    ]
