# Generated by Django 5.1.2 on 2026-01-20 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0070_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarNotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('notification_last_received_at', models.DateTimeField(blank=True, null=True)),
                ('platform_uuid', models.CharField(max_length=1024, unique=True)),
                ('unique_key', models.CharField(max_length=256, unique=True)),
                ('raw', models.JSONField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='bots.calendar')),
            ],
        ),
    ]
