# Generated by Django 5.1.2 on 2026-01-21 07:30

from django.db import migrations
from django.utils import timezone


def request_sync_for_all_connected_calendars(apps, schema_editor):
    """
    Set sync_task_requested_at for all calendars in the connected state.
    This will cause the scheduler to pick them up for syncing, which will
    create the notification channels.
    """
    Calendar = apps.get_model('bots', 'Calendar')
    # CalendarStates.CONNECTED = 1
    CONNECTED_STATE = 1
    now = timezone.now()
    
    updated_count = Calendar.objects.filter(state=CONNECTED_STATE).update(
        sync_task_requested_at=now
    )
    print(f"Requested sync for {updated_count} connected calendars")


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0071_calendarnotificationchannel'),
    ]

    operations = [
        migrations.RunPython(
            request_sync_for_all_connected_calendars,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
