# Generated by Django 5.1.14 on 2026-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0072_backfill_request_sync_for_all_calendars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
