# Generated by Django 5.1.14 on 2026-01-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0073_alter_calendarevent_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmediarequest',
            name='loop',
            field=models.BooleanField(default=False),
        ),
    ]
