# Generated by Django 5.1.14 on 2026-02-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0074_botmediarequest_loop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmediarequest',
            name='loop',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
