# Generated by Django 5.1.2 on 2025-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_organization_is_managed_zoom_oauth_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_app_sessions_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
