# Generated by Django 5.1.2 on 2025-12-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_organization_is_app_sessions_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_managed_zoom_oauth_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
