# Generated by Django 5.1.2 on 2025-12-15 19:36

from django.db import migrations


def enable_managed_zoom_oauth_for_all_organizations(apps, schema_editor):
    # Get the historical model
    Organization = apps.get_model('accounts', 'Organization')
    
    # Update all organizations
    Organization.objects.all().update(is_managed_zoom_oauth_enabled=True)


def reverse_managed_zoom_oauth_enablement(apps, schema_editor):
    # No reverse operation needed, but included for completeness
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_organization_is_managed_zoom_oauth_enabled'),
    ]

    operations = [
        migrations.RunPython(enable_managed_zoom_oauth_for_all_organizations, reverse_managed_zoom_oauth_enablement),
    ]
